version: "3.8"

services:
  local-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sigovia-local-db
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "dockerStrongPwd123"
    ports:
      - "1433:1433"
    networks:
      - sigovia-network
    volumes:
      - sqlserver-data:/var/opt/mssql

  backend:
    image: sigovia-backend
    container_name: sigovia-backend
    env_file:
      - ./.dev.env
    ports:
      - "8080:8080"
    depends_on:
      - local-db
    networks:
      - sigovia-network

networks:
  sigovia-network:
    driver: bridge

volumes:
  sqlserver-data:
