version: "3.8"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sigovia-local-db
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "dockerStrongPwd123"
    ports:
      - "1433:1433"
    networks:
      - sigovia-network
    volumes:
      - sqlserver-data:/var/opt/mssql

  backend:
    image: sigovia-backend # Assuming you've already built this image
    container_name: sigovia-backend
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DefaultConnection: "Server=sigovia-local-db,1433;Database=DevDatabase;User Id=sa;Password=dockerStrongPwd123;TrustServerCertificate=True;"
    ports:
      - "8080:8080"
    depends_on:
      - sqlserver
    networks:
      - sigovia-network

networks:
  sigovia-network:
    driver: bridge

volumes:
  sqlserver-data:
