# Run from the root folder
# ````
# docker-compose -f config/docker-compose.yml up --build
# ````

services:
  local-db:
    build:
      context: ..
      dockerfile: config/database.Dockerfile
    container_name: sigovia-local-db
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "dockerStrongPwd123"
    ports:
      - "1433:1433"
    networks:
      - sigovia-network

  backend:
    build:
      context: ..
      dockerfile: config/server.Dockerfile
    container_name: sigovia-backend
    env_file:
      - .server-in-container.env
    ports:
      - "8080:8080"
    depends_on:
      - local-db
    networks:
      - sigovia-network

networks:
  sigovia-network:
    driver: bridge
